package necesjv.date;

public class PatternDate {
    public static final String[] spatternDate = {
        "YYYY/MM/DD","YYYY.MM.DD","YYYY-MM-DD","YYYYMMDD",
        "DD/MM/YYYY","DD.MM.YYYY","DD-MM-YYYY","DDMMYYYY",
        "MMDDYYYY", "MM/DD/YYYY","MM-DD-YYYY","MM.DD.YYYY",
        "YYYYDDMM","YYYY/DD/MM","YYYY-DD-MM","YYYY.DD.MM",
        "YYYYMMDD HH,MM,SS","YYYYMMDDHH,MM,SS","YYYYMMDD HHMISS","YYYYMMDDHHMISS",
        "YYYYMMDD HH,MM",
        "YYYYMMDDHH,MM",
        "YYYYMMDD HHMI",
        "YYYYMMDDHHMI",
        "YYYY/MM/DD HH,MM,SS",
        "YYYY/MM/DDHH,MM,SS",
        "YYYY/MM/DD HHMISS",
        "YYYY/MM/DDHHMISS",
        "YYYY/MM/DD HH,MM",
        "YYYY/MM/DDHH,MM",
        "YYYY/MM/DD HHMI",
        "YYYY/MM/DDHHMI",
        "YYYY-MM-DD HH,MM,SS",
        "YYYY-MM-DDHH,MM,SS",
        "YYYY-MM-DD HHMISS",
        "YYYY-MM-DDHHMISS",
        "YYYY-MM-DD HH,MM",
        "YYYY-MM-DDHH,MM",
        "YYYY-MM-DD HHMI",
        "YYYY-MM-DDHHMI",
        "YYYY.MM.DD HH,MM,SS",
        "YYYY.MM.DDHH,MM,SS",
        "YYYY.MM.DD HHMISS",
        "YYYY.MM.DDHHMISS",
        "YYYY.MM.DD HH,MM",
        "YYYY.MM.DDHH,MM",
        "YYYY.MM.DD HHMI",
        "YYYY.MM.DDHHMI",
        "YYYYDDMM HH,MM,SS",
        "YYYYDDMMHH,MM,SS",
        "YYYYDDMM HHMISS",
        "YYYYDDMMHHMISS",
        "YYYYDDMM HH,MM",
        "YYYYDDMMHH,MM",
        "YYYYDDMM HHMI",
        "YYYYDDMMHHMI",
        "YYYY/DD/MM HH,MM,SS",
        "YYYY/DD/MMHH,MM,SS",
        "YYYY/DD/MM HHMISS",
        "YYYY/DD/MMHHMISS",
        "YYYY/DD/MM HH,MM",
        "YYYY/DD/MMHH,MM",
        "YYYY/DD/MM HHMI",
        "YYYY/DD/MMHHMI",
        "YYYY-DD-MM HH,MM,SS",
        "YYYY-DD-MMHH,MM,SS",
        "YYYY-DD-MM HHMISS",
        "YYYY-DD-MMHHMISS",
        "YYYY-DD-MM HH,MM",
        "YYYY-DD-MMHH,MM",
        "YYYY-DD-MM HHMI",
        "YYYY-DD-MMHHMI",
        "YYYY.DD.MM HH,MM,SS",
        "YYYY.DD.MMHH,MM,SS",
        "YYYY.DD.MM HHMISS",
        "YYYY.DD.MMHHMISS",
        "YYYY.DD.MM HH,MM",
        "YYYY.DD.MMHH,MM",
        "YYYY.DD.MM HHMI",
        "YYYY.DD.MMHHMI",
        "DDMMYYYY HH,MM,SS",
        "DDMMYYYYHH,MM,SS",
        "DDMMYYYY HHMISS",
        "DDMMYYYYHHMISS",
        "DDMMYYYY HH,MM",
        "DDMMYYYYHH,MM",
        "DDMMYYYY HHMI",
        "DDMMYYYYHHMI",
        "DD/MM/YYYY HH,MM,SS",
        "DD/MM/YYYYHH,MM,SS",
        "DD/MM/YYYY HHMISS",
        "DD/MM/YYYYHHMISS",
        "DD/MM/YYYY HH,MM",
        "DD/MM/YYYYHH,MM",
        "DD/MM/YYYY HHMI",
        "DD/MM/YYYYHHMI",
        "DD-MM-YYYY HH,MM,SS",
        "DD-MM-YYYYHH,MM,SS",
        "DD-MM-YYYY HHMISS",
        "DD-MM-YYYYHHMISS",
        "DD-MM-YYYY HH,MM",
        "DD-MM-YYYYHH,MM",
        "DD-MM-YYYY HHMI",
        "DD-MM-YYYYHHMI",
        "DD.MM.YYYY HH,MM,SS",
        "DD.MM.YYYYHH,MM,SS",
        "DD.MM.YYYY HHMISS",
        "DD.MM.YYYYHHMISS",
        "DD.MM.YYYY HH,MM",
        "DD.MM.YYYYHH,MM",
        "DD.MM.YYYY HHMI",
        "DD.MM.YYYYHHMI",
        "MMDDYYYY HH,MM,SS",
        "MMDDYYYYHH,MM,SS",
        "MMDDYYYY HHMISS",
        "MMDDYYYYHHMISS",
        "MMDDYYYY HH,MM",
        "MMDDYYYYHH,MM",
        "MMDDYYYY HHMI",
        "MMDDYYYYHHMI",
        "MM/DD/YYYY HH,MM,SS",
        "MM/DD/YYYYHH,MM,SS",
        "MM/DD/YYYY HHMISS",
        "MM/DD/YYYYHHMISS",
        "MM/DD/YYYY HH,MM",
        "MM/DD/YYYYHH,MM",
        "MM/DD/YYYY HHMI",
        "MM/DD/YYYYHHMI",
        "MM-DD-YYYY HH,MM,SS",
        "MM-DD-YYYYHH,MM,SS",
        "MM-DD-YYYY HHMISS",
        "MM-DD-YYYYHHMISS",
        "MM-DD-YYYY HH,MM",
        "MM-DD-YYYYHH,MM",
        "MM-DD-YYYY HHMI",
        "MM-DD-YYYYHHMI",
        "MM.DD.YYYY HH,MM,SS",
        "MM.DD.YYYYHH,MM,SS",
        "MM.DD.YYYY HHMISS",
        "MM.DD.YYYYHHMISS",
        "MM.DD.YYYY HH,MM",
        "MM.DD.YYYYHH,MM",
        "MM.DD.YYYY HHMI",
        "MM.DD.YYYYHHMI",
        "MMDD",
        "MM/DD",
        "MM-DD",
        "MM.DD",
        "DDMM",
        "DD/MM",
        "DD-MM",
        "DD.MM",
        "MDD",
        "M/DD",
        "M-DD",
        "M.DD",
        "DDM","DD/M","DD-M","DD.M"
    };
}
